### ISSUE TITLE
Simulated Scale

### ISSUE THREAD

**Issue by Foodlenz** [RichSteini/NotPlater#10]
The scale of the preview simulated name plate doesn't match the in game version of it. Not sure if it's taking into account the players UI scale or something?

Preview Window
![image](https://github.com/RichSteini/NotPlater/assets/72258441/5dd0d72a-fa33-46b4-8085-a53600908132)

Actual In World
![image](https://github.com/RichSteini/NotPlater/assets/72258441/16dc9c0b-c359-463a-a564-95854f559229)

**Comment by RichSteini** [comment]
Very good point, the problem was that i set the parent of the simulator frame to UIParent and therefore it was affected by UI scaling. Looking at the image you posted i thought it would also be good to have an option for setting the size of the simulator frame, you can do that now in the config dialog (Simulator option). Fixed and implemented in [Change parent of simulator frame, add sizing options](https://github.com/RichSteini/NotPlater/commit/841758b0aef0e618a1413bee1e3b9a629b54f276).
