### ISSUE TITLE
[Castbar] Castbars sometimes not disapearing or not showing Castprogress

### ISSUE THREAD

**Issue by Wathsup** [RichSteini/NotPlater#6]
Issue:
Nameplate Castbars sometimes does not disapear after a cast is interrupted or completed. Also in some situations, the Castbar Progress is not shown on the Nameplate Castbar (see Streamble Links for a example of both problems).

- Not Castbar Progress: https://streamable.com/qi11ih
- Castbar not disapearing: https://streamable.com/mii0ci

I dont know exactly what is casuing this Problem but wanted to put it out here in case other people have the same Problem.

**Comment by RichSteini** [comment]
That is a 2.4.3 client default castbar bug, you can resolve it by rebooting your PC. NotPlater only changes the appearance of the default castbar, to solve this issue i would have to implement a custom frame for the castbar. I am going to do that when i have time since it is a really annoying issue, for now just restart your PC and the issue will go away.

**Comment by RichSteini** [comment]
Fixed in [Castbar fix and complete project restructure](https://github.com/RichSteini/NotPlater/commit/509755b5afb6004f29779735e7be2c9c07427feb).
